### PR TITLE
Add more instantiate.jl tests

### PR DESCRIPTION
**Pull request by zdroid**

### CODE REVIEW

**Comment by zdroid** [comment]
@tlienart Any idea why purgecss doesn't work in the testing environment?

**Comment by tlienart** [comment]
well it's not installed on travis right?

**Comment by zdroid** [comment]
@tlienart It's work done by Travis anyway, so we can just relax. :smile: It could help us verify that purgecss process doesn't break with some code change or a different dependency, without testing it manually. And it's almost 100% coverage.

**Comment by tlienart** [comment]
ah sorry I was unclear, I meant that I don't know how to install such dependencies on travis (that's the bit that seemed like work). 

So if you can figure out how the `.travis.yml` needs to be adjusted to install `purgecss` and get it to be called, then it'd be great. Potentially it's just a matter of copying the stuff from the deploy.ymlk https://github.com/tlienart/PkgPage.jl/blob/9e475ff26ea9ec5ff5fe6d3b9df20312c87d3d76/.github/workflows/DeployPage.yml#L39-L46

**Comment by tlienart** [comment]
hmm that will try to install every single time you run the tests, it'd be better to have this in the travis script **or** to at least have a test checking whether require('purgecss') works and if it doesn then skip the install

Thanks for this!

**Comment by zdroid** [comment]
@tlienart I think it'll produce the same result anyway, but you can add the require check.

**Comment by tlienart** [comment]
well I'm not ok for the installation on every single test as mentioned above; and haven't had the time to do it myself (am looking now though)

**Comment by tlienart** [comment]
now good

**Pull request merged**
