### PR TITLE
Ship with FranklinUtils

### PR DESCRIPTION
**Pull request by zdroid**
Utils weren't public API anyway, so I think this is safe for merging.

### CODE REVIEW

**Comment by tlienart** [comment]
this needs a release of FranklinUtils before it can be merged right?

**Comment by tlienart** [comment]
I'll merge this when https://github.com/JuliaRegistries/General/pull/20351 is in

**Comment by tlienart** [comment]
Happy to merge this when tests are passing, thanks!

**Comment by zdroid** [comment]
@tlienart done!

**Pull request merged**
